### ISSUE TITLE
Implement support for .debug_loc

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#104]
Section 2.6.2 Location Lists

**Comment by fitzgen** [comment]
For both the start and end address offsets:

> This address offset has the size of an address and is relative to the applicable base address of the compilation unit referencing this location list.

We should new-type these so we/users don't accidentally use them as absolute addresses or anything like that.

**Comment by philipc** [comment]
I don't think there is a need for new-types. The base address handling is the same as for .debug_ranges, and we currently add the base address while parsing them. Have a look at .debug_ranges and let me know if you still think it needs new-types.

**Comment by fitzgen** [comment]
Ah, ok that WFM
