### ISSUE TITLE
Should the offset newtypes be usize?

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#119]
The values of DebugInfoOffset etc nearly always need to be used as usize, not u64. Perhaps we should change them to usize?

Note that `offset.0 as usize` will truncate if usize is smaller than u64, so if we validate this when parsing then I think overall this will be safer. I can't see any way to support offsets that are larger than the host's usize anyway, so I think failing when parsing is all we can do.

**Comment by fitzgen** [comment]
Yeah, SGTM

> Note that offset.0 as usize will truncate if usize is smaller than u64, so if we validate this when parsing then I think overall this will be safer. I can't see any way to support offsets that are larger than the host's usize anyway, so I think failing when parsing is all we can do.

Totally.
