### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#123]
@jvns @kamalmarhubi: you're the first to use `gimli` outside of those of us who've been deep in the guts of the implementation, do you have any suggestions on how we could improve documentation?

@jvns, I'm particularly interested because you mention that `gimli` wasn't all that much better documented than libdwarf in your rustconf keynote, and I'm wondering if there's specific points you think we could improve on, or if things have improved at all since then.

Thanks a ton for your feedback!

**Comment by kamalmarhubi** [comment]
I haven't looked too recently so I can't comment much. I actually don't recall finding docs difficult, but it was @jvns who did most of the port to gimli. There are a few areas I think the API could be improved though; I'll see if I can remember what they were and file some issues.

**Comment by jvns** [comment]
heh i think i didn't say that very well :(. i really thought it was super easy to use!! the example dwarfdump program was the most important thing for me and I could learn basically everything I wanted from that program

**Comment by fitzgen** [comment]
> There are a few areas I think the API could be improved though; I'll see if I can remember what they were and file some issues.

Awesome, thanks! :)

> the example dwarfdump program was the most important thing for me and I could learn basically everything I wanted from that program

Great to hear! :)

-----------------------------------------

I'm going to leave this issue open for some more overview-y/intro-y kind of documentation I'd like to write in lib.rs in the near future.

**Comment by philipc** [comment]
This isn't really actionable. Open a new issue if there's something specific that should be done.
