### ISSUE TITLE
Implement SiblingEntriesIter on top of EntriesCursor

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#13]
I imagine this would best be exposed via `DebuggingInformationEntry::children(&self) -> SiblingEntriesIter` where the siblings are the original entry's first child and its siblings.

**Comment by philipc** [comment]
@fitzgen Do you still see a need for this? Does `EntriesTree` cover the use cases for this? This wouldn't be hard to add, but I think it might make it easy for the user to use in a way that means they are needlessly parsing entries multiple times.

**Comment by fitzgen** [comment]
If we ever find the need to do this based on usage experience, then let's do it at that time.
