### ISSUE TITLE
Implement a DfsEntiesIter which yields items of (dfs_depth, DIE)

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#14]
I imagine that this would be exposed on the various unit types: `FooUnit::dfs_entries(&self) -> DfsEntriesIter`.

Could also have another type of DFS iterator that maintains the stack of parents for the current entry, yielding iteration items like: `(&Vec<DIE>, DIE)`. Wouldn't want to impose the cost of a vec on users who didn't want it though, so this shouldn't be the only/default option.

**Comment by philipc** [comment]
@fitzgen Do we still need this? I think `EntriesCursor` has morphed into an DFS iterator already (just with a `next_dfs` method instead of `next`).

**Comment by fitzgen** [comment]
Yeah we can close this.
