### ISSUE TITLE
Support DWARF version 5 operations and corresponding GNU extensions

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#140]
My rust binaries are linked with objects that use `DW_OP_GNU_entry_value`. Now that gimli's dwarfdump is displaying locs, it panics when trying to dump my rust binaries.

I think I've seen `DW_OP_GNU_implicit_pointer` in use somewhere too.

DWARF 5 operations:
- [x] DW_OP_implicit_pointer
- [x] DW_OP_addrx
- [x] DW_OP_constx
- [x] DW_OP_entry_value
- [x] DW_OP_const_type
- [x] DW_OP_regval_type
- [x] DW_OP_deref_type
- [x] DW_OP_xderef_type
- [x] DW_OP_convert
- [x] DW_OP_reinterpret

**Comment by tromey** [comment]
`dwarf2.def` lists the GNU extensions and in most cases provides a link to documentation:

https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob;f=include/dwarf2.def;h=64850714ca436e988a11dfeef4d22ea0dc437c59;hb=HEAD#l598

Not all of these are in active use.  `DW_OP_GNU_encoded_addr` isn't implemented by gdb, so probably not used.  IIRC `DW_OP_GNU_uninit` isn't generated by GCC by default.  The others can be generated though.  Note that the typed stack stuff will need relatively large changes to the evaluator.

**Comment by tromey** [comment]
Also, I think it would be better not to panic when dumping something unknown.

**Comment by philipc** [comment]
> Also, I think it would be better not to panic when dumping something unknown.

Yeah, gimli's dwarfdump currently uses `expect` everywhere. This is fine as a validation tool. Definitely should be fixed if dwarfdump is going to see general usage, but that's not a high priority goal for me now (and if that were the goal, then I would probably stop trying to clone libdwarf's dwarfdump output so closely).

**Comment by tromey** [comment]
The DWARF 5 draft is out now and promotes these to standard.

**Comment by philipc** [comment]
`DW_OP_implicit_pointer` and `DW_OP_entry_value` implemented in #150

**Comment by tromey** [comment]
I started work on this here: https://github.com/tromey/gimli/tree/dwarf-5-eval.  But it needs a rebase and isn't complete.

**Comment by philipc** [comment]
Typed operations were implemented in #293. `DW_OP_addrx ` was started in #242.

**Comment by philipc** [comment]
DW_OP_addrx and DW_OP_constx were implemented in #358. All done!
