### ISSUE TITLE
Figure out how to speed up OSX runs on Travis CI

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#144]
This one timed out and was killed by Travis CI, and was reported as a failure: https://travis-ci.org/gimli-rs/gimli/jobs/165874003

We should figure out how to speed them up so that this doesn't become a recurring problem.

**Comment by fitzgen** [comment]
One idea: cache the `.rustup` directory in addition to `.cargo`?

**Comment by fitzgen** [comment]
I restarted the job, which I guess throws away the old logs. Lame. Basically, we timed out while doing a rustup for stable rust.

**Comment by philipc** [comment]
A big chunk of the OSX time is installing python for travis-cargo. Is it possible to cache that? I'm not sure that travis-cargo is providing much benefit, so we could also try replacing it with shell scripts.

**Comment by fitzgen** [comment]
> A big chunk of the OSX time is installing python for travis-cargo. Is it possible to cache that?

Yes, I think so: https://docs.travis-ci.com/user/caching/#Arbitrary-directories

> I'm not sure that travis-cargo is providing much benefit, so we could also try replacing it with shell scripts.

I'd like to do this only if caching the python/pip/brew stuff doesn't solve our problems.

**Comment by philipc** [comment]
OSX times in Travis are fine now.
