### ISSUE TITLE
Make examples/dwarfdump.rs's output format match the "real" dwarfdump

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#15]

**Comment by philipc** [comment]
Not sure if it belongs in this issue, but one possibility is that if we make the output an exact clone, then we could reuse some of the dwarfdump regression tests.

**Comment by fitzgen** [comment]
I've made and landed an initial mini clone.

It doesn't match the format of the output, but this is a swell idea. We could also compare performance between the two.

**Comment by philipc** [comment]
I'm starting to work on making the .debug_info format match dwarfdump.

For performance comparisons, I did some basic benchmarks at https://github.com/philipc/dwarf-bench, but I couldn't avoid IO for the libdwarf/elfutils benchmarks, so it was hard to get anything reliable and I'm not going to pursue that further currently. The benchmarks did show that gimli is already much faster (that's including IO in the gimli test too). I also think that both the libdwarf and elfutils APIs are much worse, at least for DIE iteration.

**Comment by fitzgen** [comment]
> The benchmarks did show that gimli is already much faster (that's including IO in the gimli test too).

\o/

> I also think that both the libdwarf and elfutils APIs are much worse, at least for DIE iteration.

\o/

**Comment by philipc** [comment]
We've been diverging from dwarfdump's output. While matching it was useful for early validation, I don't think it's as useful anymore. If we were going to match another tool's output, then I think readelf or llvm-dwarfdump would be better candidates.
