### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by jonhoo** [gimli-rs/gimli#176]
It'd be great if we could cut a new gimli version soon. [addr2line](https://github.com/gimli-rs/addr2line) needs #164 and #165 in order to compile, so it's currently required to use gimli as a git dependency. Once a new release is cut, it can move both gimli and owning-ref (following the release of [0.2.4](https://github.com/Kimundi/owning-ref-rs/commit/c00676ea361eae657cfda05bf14fbca3390d0a23)) to regular, versioned dependencies, which will allow us to start pushing to crates.io again.

/cc @philipc @fitzgen

**Comment by philipc** [comment]
I published 0.11.0.
