### ISSUE TITLE
Make it possible to resume a line number program from a sequence boundary

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#178]
In order to make it possible to address things like gimli-rs/addr2line#29 while maintaining reasonable performance I'd like to be able to resume the line number program from a sequence boundary.

The correct state of the `LineNumberProgramHeader` and an offset into the line number program are all that are required to restart a line number program from a sequence boundary.  And almost all of the `LineNumberProgramHeader` state is immutable, except for the table of file names.  To solve that I propose to share a table of file names between `LineNumberProgramHeader`s that are cloned from one another.  That gives us an API that looks like (in pseudo-Rust)

```
pub struct LineNumberProgramHeader {
  // existing immutable bits
  file_names: Arc<Mutex<Vec<FileEntry>>>
  valid_files: usize;
}

pub struct PausedLineNumberProgram {
  valid_files: usize,
  rest: // whatever type this is,
}

impl StateMachine {
  fn resume(header: LineNumberProgramHeader, rest: Whatever) -> Self {
    // make default row
    let opcodes = OpcodesIter {
      input: rest,
      endian: PhantomData,
    };
    StateMachine {
      header: header,
      row: row,
      opcodes: opcodes,
    }
  }

  pub fn save(&self) -> PausedLineNumberProgram {
    assert!(end_sequence())
    PausedLineNumberProgram {
      valid_files: self.valid_files,
      rest: rest_of_the_program(),
    }
  }
}

impl LineNumberProgramHeader {
  fn define_file(filename) {
    // Add filename if file_names.len() == valid_files, valid_files++
    // else ignore (debug_assert! matching, perhaps)
  }

  fn get_file(index) {
    // Bound returned filenames from file_names by valid_files
  }

  pub fn resume(&self, lnp: &PausedLineNumberProgram) -> StateMachine {
    let mut header = self.clone();
    header.valid_files = lnp.valid_files;
    StateMachine::resume(header, lnp.rest)
  }
}
```

If you don't like foisting the `Arc<Mutex<>>` onto everyone (and I suspect you won't) we can introduce a trait or something to let the user determine whether or not they need thread safety.

Thoughts?

CC @fitzgen @philipc @jonhoo

**Comment by philipc** [comment]
Can you describe the algorithm that addr2line would use?

Here's the algorithm I think it should use. I haven't tried to align this with your proposed changes.
1. Parse the line number program header.
2. Iterate through all line number rows, and record a  Vec of (offset, start_address, end_address) for each sequence. Also updates the file name list if required.
3. Sort the Vec of sequences.
4. For each address to lookup, binary search to find the sequence containing the address (can there be more than one?)
5. Iterate through the line number rows starting at the offset for that sequence to find the row for the address. This iteration would never update the file name list.

Step 2 could use an optimized iterator that doesn't return full rows.

**Comment by khuey** [comment]
I was imagining something similar, except only going through the program as far as we need to to perform any given lookup.  Then on a subsequent lookup we'd look at the Vec and go to the matching sequence if it exists, or to the point where we stopped previously and continue from there if it doesn't.

 If we do go through all the line number rows the first time we do a lookup in a CU that does eliminate the weird handling of file names.  That's a nice benefit.

**Comment by philipc** [comment]
Yes, simplifying the file name handling is the main reason I want to do it that way. It also avoids needing to sort more than once.

**Comment by fitzgen** [comment]
Both approaches seem reasonable to me.

-------------------------

```rust
  fn define_file(filename) {
    // Add filename if file_names.len() == valid_files, valid_files++
    // else ignore (debug_assert! matching, perhaps)
  }
```

The debug_assert is to assert that the file name we would have added matches the one that is there already, right?

-------------------------

I wonder if we should parameterize the line number program / header with a generic filename store type, so we can use `Rc` and `RefCell` instead of `Arc` and `Mutex` if thread safety isn't required. Maybe this is overengineering, and the full initial pass is a better approach.

**Comment by khuey** [comment]
I think the full initial pass is fine.
