### ISSUE TITLE
DWARF5 support

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#183]
http://www.dwarfstd.org/doc/DWARF5.pdf

There appear to be some non-backwards compatible changes.  I don't know when we'll start seeing compilers output DWARF 5.

**Comment by tromey** [comment]
GCC can already emit DWARF 5.  You can search for `dwarf_version` here to see details of what it does: https://gcc.gnu.org/viewcvs/gcc/trunk/gcc/dwarf2out.c?view=co&revision=245052&content-type=text%2Fplain

I didn't check to see if this work made it into a released GCC yet.

**Comment by khuey** [comment]
Dupe of #140
