### ISSUE TITLE
Add a mechanism for asynchronously evaluating a DWARF expression.

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#184]
The gimli embedding provides the inputs needed to evaluate a DWARF expression by implementing the `EvaluationContext` trait.  In the system I'm building, getting register and memory values requires a database lookup (potentially on another machine if we're `evaluate_entry_value()`ing and subprogram entry was far enough away in time).

Spinning up a thread for evaluating the expression and blocking there works, but what I'd really like is an `Evaluation` that takes an `AsyncEvaluationContext` that returns futures and has an `evaluate` that returns a `Future<Item=Vec<Piece>>`.

I started hacking this up but doing it without duplicating much of the evaluation code is difficult and/or impossible :/

**Comment by fitzgen** [comment]
Yeah, I don't know if Rust provides a way to be generic across synchronous and asynchronous evaluation. I haven't tried, but I suspect it would be tricky.

**Comment by tromey** [comment]
Perhaps the base implementation could be async and we could wrap sync evaluation contexts in something that just returns resolved futures.

**Comment by khuey** [comment]
`futures-rs` has built in support for converting `Result`s to immediately resolvable futures.  Doing it this way does mean introducing an unconditional dependency on `futures-rs` though.

**Comment by tromey** [comment]
Another idea would be to keep the evaluator state in a struct, provide a way to evaluate operations until some contextual data is needed, and then have the evaluator return an enum that holds either a final result (a piece vector) or a contextual request.  This is basically the same effect as futures but without the dependency on `futures-rs`; pushing any asynchrony to the user.
