### ISSUE TITLE
Add the ability to lookup DIEs from DebugInfoRef/UnitRef

### ISSUE THREAD

**Issue by jrmuizel** [gimli-rs/gimli#196]
This is needed to resolve types of parameters for subroutines.

**Comment by philipc** [comment]
Does [`entries_at_offset`](https://github.com/gimli-rs/gimli/blob/d591dc4912b9742990aea5c38fe7ea917fbce0d0/src/unit.rs#L244)  meet your needs for `UnitRef`?

For `DebugInfoRef`, probably what we want is something to convert a `DebugInfoOffset` to a `UnitOffset` for a given unit. It will be up to the caller to cache the units. That may change if we add more caching to gimli.

**Comment by jrmuizel** [comment]
That sounds reasonable, although needing to have unit is a bit heavy weight. It would be nice to be able to just read a given DIE

**Comment by philipc** [comment]
We need the information from the associated unit header in order to be able to read the DIE though.

**Comment by jrmuizel** [comment]
Ah, ok then. Your plan sounds reasonable.

**Comment by philipc** [comment]
I've added some conversions between offsets in #199.
