### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#20]
gimli is currently about twice as slow as rust-dwarf. Need to figure out why and see if gimli can be improved to the same or better speed.

I'm currently tracking down a performance bug in rust-dwarf (due to making endian generic). It's looking like a codegen bug in rustc, so hopefully what I learn from that will be applicable to gimli too.

**Comment by fitzgen** [comment]
Yikes.

Twice as slow doing what? DIE tree traversal? Are you measuring using the benches or something else?

If we profile and find which operations that dominate the results, it would be nice to add micro benches for those operations.

**Comment by philipc** [comment]
DIE tree traversal. I added a benchmark in rust-dwarf that uses gimli for comparison purposes.

**Comment by philipc** [comment]
`perf` shows that 40% of the time is spent in `bench_parsing_debug_info`. There is some inlining occurring, but a lot of it seems to be that all the `ParseResult` handling optimizes poorly. For example, we call `cursor.current`, and the result is copied around on the stack at least 3 times in quick succession. It doesn't help that the result is a `DebuggingInformationEntry` value, rather than a reference, so there's more to copy.

I've also spent a bit more time on the rust-dwarf regression, but the problem there is affected by MIR, so it might be worth waiting for MIR to stabilize before spending too much time looking at performance. I did find another problem there that I had to use `unsafe` to avoid, and the root cause of it seemed to be `Result` handling too.

**Comment by philipc** [comment]
`perf` reports `parse_unsigned_leb` at about 6.5%. Copying `leb128::read::unsigned` into `parse_unsigned_leb` (and fixing the error return values) changes that to about 2.5%. Hand coding the `read_exact` further reduces that to 1.5%. Note that `leb128::read::unsigned` was already being inlined. Looking at the assembly, the main difference is the amount of error handling code, and some of it is showing as hot spots. I think that having different error types for gimli and leb128 is bad (and similar for the io error type for `read_exact`).

**Comment by fitzgen** [comment]
Wow, that's unexpected and unfortunate. I guess we should just manually inline it all and stop using a separate crate for LEB128 parsing?

**Comment by philipc** [comment]
Yes we may need to do that, which I agree is unfortunate. If may be worth investigating if rustc can be changed to optimize this better.

**Comment by tromey** [comment]
Just FWIW -- leb parsing was pretty much the only bit of DWARF reading in gdb that benefited from optimization.  It's important to inline it.

**Comment by fitzgen** [comment]
Dumb low hanging fruit: c61b35f04a4b3278814ade668a2db9c34c1fc5e1

**Comment by philipc** [comment]
Is `leb128::read::unsigned` still being inlined now that `parse_unsigned_leb` is inlined? (I would check myself but I probably won't get to it for a few days.)

**Comment by fitzgen** [comment]
Funky. It looks like `parse_unsigned_leb` isn't always (ever?) getting inlined. Maybe those speedups were just from inlining `parse_u8` and friends? Those ones are indeed getting inlined.

It appears that `leb128::read::unsigned` is still getting inlined into `parse_unsigned_leb`, but we should probably add `#[inline]` to `leb128`s exported functions to be sure and express our intent to the compiler. In fact, I am actually surprised that it gets inlined at all across crates without that attribute.

**Comment by fitzgen** [comment]
> In fact, I am actually surprised that it gets inlined at all across crates without that attribute.

I just realized that `leb128::read::unsigned` is generic, so it has to appear in serialized form in the compiled crate to allow new specializations, and this ends up also allowing inlining.

**Comment by philipc** [comment]
I notice that `constants.rs` is using `u64` for constants that will never be that large. This probably has some cost.

**Comment by fitzgen** [comment]
> I notice that constants.rs is using u64 for constants that will never be that large. This probably has some cost.

The reason I initially switched them all to u64 was because we read them from leb128 which returns u64 and it also lets us precisely represent unknown variants.

Switching to a smaller representation will need to start range checking whenever we read these types.

**Comment by philipc** [comment]
By the way, gimli performance is now comparable to rust-dwarf, so I'll use this issue just to record random things I notice until I get back to looking at performance properly. One of those random things is that 9286858c improved the debug_info performance, but I can't explain why.

2ae61e361eb85d7684b11a092bd2ba7384859de5 test bench_parsing_debug_info                  ... bench:   2,993,722 ns/iter (+/- 62,450)
9286858c7db26c6f78da07bbf981409599662285 test bench_parsing_debug_info                  ... bench:   2,789,972 ns/iter (+/- 68,726)

I measured this a couple of times to check.

**Comment by philipc** [comment]
Not sure this issue contains anything of value now. Performance improvements are ongoing. The main concerns I still have are poor optimization of moves by the compiler, but that's being improved in the compiler, and is not something we can fix here.
