### ISSUE TITLE
Mapping from dwarf registers to processor registers.

### ISSUE THREAD

**Issue by xd009642** [gimli-rs/gimli#200]
The ability to map from dwarf registers to processor registers would be useful when using the debug_frames section. For example if we look at the [x86_64 ABI](https://software.intel.com/sites/default/files/article/402129/mpx-linux64-abi.pdf), we can see that dwarf register 7 is the Stack Pointer Register.

Filling in this mapping for the various architectures would definitely make working with the DWARF tables easier and I'd be willing to help implement this if you guys think it would be useful.

Edit: Unsure how to add labels but this would be an enhancement obviously

**Comment by fitzgen** [comment]
We have that table embedded in our documentation: https://docs.rs/gimli/0.13.0/gimli/struct.UnwindTableRow.html#method.register

I recall some discussion about the best way to provide the register mapping for the target architecture, but don't think we came up with a good solution. Ideas welcome :)

**Comment by xd009642** [comment]
Hmmm, I'll have a think about it. I submitted a PR to libc regarding the x86 and x86_64 registers. If the register structs get accepted would you be opposed to adding a libc dependency and leveraging some of the structures it'll provide if it makes a solution nicer?

**Comment by fitzgen** [comment]
Do you have a link to the PR you submitted?

**Comment by xd009642** [comment]
https://github.com/rust-lang/libc/pull/599 I've just seen it failed the clippy checks with trailing whitespace but I'll fix that when I get home from work

**Comment by philipc** [comment]
Is `user_regs_struct` only used with ptrace?

It might be better if a mapping between DWARF register indices and fields in user_regs_struct is kept in whatever crate is using ptrace, since it will have the libc dependency already.

Would it help if gimli defined an enumeration for the register indices?

**Comment by tromey** [comment]
> Is user_regs_struct only used with ptrace?

Also I think core files and the gdb remote protocol.

**Comment by xd009642** [comment]
It might be worth adding some higher level functionality regarding the user_regs_struct to nix-rust as libc only deals with direct bindings. Then leverage those features from nix-rust. I'm currently away from my development machine for the bank holiday so won't get a chance to look properly into this until Tuesday. 

My initial thoughts right now are an enum for the register indices for x86_64 registers and dwarf registers with convert to and from functions in rust_nix. And then use the register enum in gimli.

**Comment by luser** [comment]
I hand-rolled some code for handling CPU contexts from minidumps:
https://github.com/luser/rust-minidump/blob/master/src/context.rs

I was thinking it would be nice to have a standalone crate that defined CPU registers for various architectures and provided ways to map between various representations, but maybe that's overkill.

**Comment by fitzgen** [comment]
> I was thinking it would be nice to have a standalone crate that defined CPU registers for various architectures and provided ways to map between various representations, but maybe that's overkill.

That sounds good to me. Could put it in the `gimli` org if you wanted. Or not. Either way.

**Comment by philipc** [comment]
#328 defines some DWARF register numbers. I don't think that mappings to other schemes belong in gimli though.
