### ISSUE TITLE
libobjc.A.dylib has `__eh_frame` CIE with version 3

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#244]
My understanding is that the only valid version for `eh_frame` is 1. IIRC, 3 is a valid version for `debug_frame` though. I wonder if this is just a buggy unwind info producer?

Here is what binutils' `dwarfdump` gives on `libobjc.A.dylib`:

```
0x00000270: CIE
        length: 0x00000014
        CIE_id: 0xffffffff
       version: 0x03
  augmentation: "zR"
    code_align: 1
    data_align: -8
   ra_register: 0x10
 aug_arg["zR"]: DW_GNU_EH_PE_pcrel + DW_GNU_EH_PE_absptr
                DW_CFA_def_cfa (rsp, 8)
                DW_CFA_offset (rip, -8)
                DW_CFA_nop
                DW_CFA_nop
  Instructions: Init State: CFA=rsp+8     rip=[rsp]
```

Will upload a copy of the section in a second.

**Comment by fitzgen** [comment]
From https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA/ehframechpt.html

> Version
>
>    Version assigned to the call frame information structure. This value shall be 1.

:-/

**Comment by fitzgen** [comment]
> IIRC, 3 is a valid version for debug_frame though. I wonder if this is just a buggy unwind info producer?

`debug_frame` CIEs in DWARF 3 use version 3.

**Comment by fitzgen** [comment]
The funky thing is, there are tons of CIEs in this section, but only one uses version 3.

**Comment by philipc** [comment]
Are we decoding the version 1 CIEs correctly? Looking at the gdb source (gdb/dwarf2-frame.c), the version field is handled identically for eh_frame and debug_frame. So I suspect our current decoding of the return address register is wrong for eh-frame version 1.

**Comment by fitzgen** [comment]
> Are we decoding the version 1 CIEs correctly?

Nope, no one is using our CFI stuff yet, AFAIK, so I don't have much faith ;)

Note that the `dwarfdump` in that command is the binutils'.

Will look into what GDB is doing when I circle back here.
