### ISSUE TITLE
Add a parser for the .gnu_debuglink section

### ISSUE THREAD

**Issue by sfackler** [gimli-rs/gimli#260]
As described in https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Debugging_with_gdb/separate-debug-files.html.

It's pretty small - just a string and a CRC value.

**Comment by fitzgen** [comment]
Aside: this would eventually be used by https://github.com/gimli-rs/moria

**Comment by fitzgen** [comment]
@sfackler are you interested in implementing this?

**Comment by sfackler** [comment]
Sure - I'll take a look.

**Comment by fitzgen** [comment]
Awesome! Let me know if you have any questions :)

**Comment by philipc** [comment]
Implemented in the object crate instead (and used by moria).
