### ISSUE TITLE
New Gimli Release

### ISSUE THREAD

**Issue by mitsuhiko** [gimli-rs/gimli#263]
Any chance we could get a new gimli release? We're currently tracking master (need `.return_address_register` on `CommonInformationEntry`) but it would be nice if we could push our crate on crates.io without having to fork off gimli on there as well.

**Comment by fitzgen** [comment]
Sounds good to me -- anything you wanted to change/fix/add before we cut another release @philipc?

**Comment by fitzgen** [comment]
If not, I can write up a change log tomorrow and publish to crates.io.

**Comment by philipc** [comment]
New release sounds good.

**Comment by fitzgen** [comment]
https://github.com/gimli-rs/gimli/pull/264

**Comment by fitzgen** [comment]
Published on crates.io

**Comment by fitzgen** [comment]
Release announcements:

* https://www.reddit.com/r/rust/comments/7gwysn/announcing_gimli_0150/
* https://users.rust-lang.org/t/gimli-a-blazing-fast-parser-for-dwarf-debugging-information/7348/14
