### ISSUE TITLE
Is the dump_file function in the dwarfdump example too magical?

### ISSUE THREAD

**Issue by iamthad** [gimli-rs/gimli#267]
The dump_file function makes heavy use of type inference for its `load_section` subfunction, inferring the types of `debug_abbrev`, `debug_ranges`, etc. from their use in the function calls below. While this is a neat demonstration of Rust's type inference abilities, it took me (admittedly a novice Rustacean) a great deal of time to understand how the right sections were getting loaded into the appropriate variables.

Given that `dwarfdump.rs` is intended as an example, is this level of "magic" appropriate?

**Comment by fitzgen** [comment]
I think the level of "magic" is appropriate, but it could certainly use short a comment about relying on type inference. Interested in making a PR?
