### ISSUE TITLE
New release for #![no_std] support

### ISSUE THREAD

**Issue by est31** [gimli-rs/gimli#303]
It would be cool to get a new release of gimli so that issue #138 is fixed on the latest release as well. This is needed so that addr2line can offer #![no_std] support itself, which is needed so that addr2line as well as gimli can be used inside the libstd library (https://github.com/gimli-rs/addr2line/issues/89, https://github.com/rust-lang/rust/issues/46439).

It is more than 6 months since the last release of gimli. I'd say it's reasonable to have a new release again.

Thanks!

**Comment by fitzgen** [comment]
@philipc was there anything else with regards to `EndianReader` that you wanted to land before we push out a new release? Or anything else in general?

Otherwise, I'm happy to push a new release.

**Comment by philipc** [comment]
No, I think it's good for a release.
