### ISSUE TITLE
`alloc` feature broken in nightly

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#309]
https://travis-ci.org/gimli-rs/gimli/builds/402095262

Haven't looked into it yet.

**Comment by philipc** [comment]
Things in the `alloc` crate are being moved around as part of stabilization (although the RFC for this is still open).

**Comment by gz** [comment]
I sent pull requests to https://github.com/sfackler/rust-fallible-iterator/pull/7
and https://github.com/Storyyeller/stable_deref_trait/pull/4 so once they release new versions and https://github.com/gimli-rs/gimli/pull/310 gets in this should be fixed.

**Comment by fitzgen** [comment]
Thanks @gz :)

**Comment by philipc** [comment]
This is fixed, but it's still failing in the tests because the crossbeam dev dependency is pulling in stable_deref_trait/std.

**Comment by philipc** [comment]
We can't make crossbeam optional, because dev dependencies can't be optional yet (https://github.com/rust-lang/cargo/issues/1596). Maybe we could fix this by fixing stable_deref_trait so that it can build when both the alloc and std features are enabled (std would override alloc).

**Comment by philipc** [comment]
Or move the examples into their own crate (gimli-utils?).

**Comment by philipc** [comment]
crossbeam no longer depends on parking_lot, so this problem has gone away.
