### ISSUE TITLE
`RequiresTextBase` should be `RequiresTextRelocationOffset`

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#332]
`DW_OP_addr` supplies an absolute address, not an address relative to the .text base address. The way it needs to be handled is that if `.text` has been relocated by an offset, then that offset needs to be added to the `DW_OP_addr` value too (rather than adding the `.text` base address). Or maybe I am misunderstanding what `.text` base address means in this context?

cc @khuey

**Comment by khuey** [comment]
Thanks for CCing me. You're correct that it is the relocation offset, not the base that matters here.

But something I didn't realize before is that the `DW_OP_addr` value doesn't have to be in the .text section. It could easily be in .data or .bss, for instance. When I landed #210 I was handling `DW_AT_GNU_call_site_value` which is obviously always in the .text section. But global variable values aren't going to be there. Not sure how to handle this ...

**Comment by philipc** [comment]
I think we need to return the address value to the caller, and let them do the relocation. They will know if it's the same relocation offset for all segments (I think this is the case for linux), and if not, they will know the address ranges for each segment and be able to determine which segment the address belongs to.

**Comment by khuey** [comment]
Reverting #210 and pawning this off on the caller sounds correct.
