### ISSUE TITLE
`EhHdrTable::lookup` requires a base address to `.eh_frame_hdr` in `BaseAdresses::data` instead of a base address to `.data` as the docs suggest

### ISSUE THREAD

**Issue by koute** [gimli-rs/gimli#350]
I've been adding support for `.eh_frame_hdr` to [our profiler](https://github.com/nokia/nperf); after a lot of debugging and tweaking I've managed to get it to work, but it was **very** confusing.

First and foremost, currently `EhHdrTable::lookup`'s prototype looks like this:

```rust
pub fn parse(&self, bases: &BaseAddresses, addr_size: u8) -> Result<ParsedEhFrameHdr<R>>
```

I see this and think - great! Let's initialize the `bases` like I usually do - `set_text` with the base address to `.text`, `set_data` with the base address to `.data` and `set_cfi` with the base address to `.eh_frame`. However, this didn't work - `EhHdrTable::lookup` (and consequently also `EhHdrTable::lookup_and_parse` since it uses `lookup`) returned incorrect results! So after a lot of trial-and-error I got it to actually work correctly with `BaseAddresses` initialized like this:

```
let mut bases = BaseAddresses::default();
bases = bases.set_cfi( eh_frame_base );
bases = bases.set_data( eh_frame_hdr_base );
```

The docs for `gimli::BaseAddresses::data` say that:

> The address of the `.data` section in memory.

...and yet here I am setting it to the base address of the `.eh_frame_hdr` instead of `.data`. Is this correct? Or is this a bug in `gimli`?

Another minor issue is that the docs for `gimli::BaseAddresses::cfi` say that:

> The address of the current CFI unwind section (`.eh_frame` or `.debug_frame`) in memory.

However `EhFrameHdr::parse` requires the `cfi` to be the address to `.eh_frame_hdr`, which is not obvious from the docs.

**Comment by philipc** [comment]
https://github.com/gimli-rs/gimli/pull/316#discussion_r207795152 is related I think, and I should have opened a bug for it at the time. So yeah, this is too easy to get wrong and we should fix it somehow.

**Comment by koute** [comment]
Perhaps we could have (at least in case of e.g. `EhHdrTable::lookup`) replace the generic `BaseAddresses` with a non-generic struct for which it would be obvious what is what? (Have `set_eh_frame` and `set_eh_frame_hdr` instead of `set_cfi` and `set_data`.)

**Comment by philipc** [comment]
I think we only need to add `set_eh_frame_hdr`. Keep `set_text`, `set_data`, and `set_cfi` (don't call it `set_eh_frame` because it needs to allow for `.debug_frame` too). Internally, `parse_encoded_pointer` will need something to indicate which base to use.

The fact that you had to call `bases.set_data( eh_frame_hdr_base )` is really weird and needs looking into further... I was only expecting there to be confusion between the `.eh_frame` and `.eh_frame_hdr` base addresses, not the `.data` base address as well.
