### ISSUE TITLE
Implement DW_AT_ranges writing

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/gimli#360]
This is needed for https://github.com/bjorn3/rustc_codegen_cranelift/issues/166 line info, because I can't rely on faerie putting functions in a certain order. And gdb doesn't accept line info when neither `DW_AT_low_pc` nor `DW_AT_high_pc`/`DW_AT_ranges` is set.

**Comment by bjorn3** [comment]
I have got a failing test :( https://github.com/bjorn3/gimli/tree/impl_range_write

**Comment by philipc** [comment]
I haven't looked in detail, but probably need to convert the raw ranges. I can have another look tomorrow. Also feel free to open a WIP PR.
