### ISSUE TITLE
ETA on the next release?

### ISSUE THREAD

**Issue by koute** [gimli-rs/gimli#414]
Is there any ETA as to when a new release of `gimli` will be made?

Some backgroud - I've added AArch64 support to [our profiler](https://github.com/nokia/not-perf) today. Unfortunately it's broken on `gimli` 0.17 (where only the CFA rule is returned with no rules for registers), however it seems to have been fixed already as the current `master` doesn't have that problem.

(Side note - I'm really loving the new interface! It's significantly more ergonomic than the old one.)

**Comment by philipc** [comment]
> Is there any ETA as to when a new release of gimli will be made?

I want to finish implementing writing of .eh_frame (currently we only write .debug_frame), since that might require some breaking changes in the write API, so maybe a week or two?

> Unfortunately it's broken on gimli 0.17

Maybe due to the code_alignment_factor (#401).
