### ISSUE TITLE
[LineProgram] Don't make LineEncoding configurable

### ISSUE THREAD

**Issue by bjorn3** [gimli-rs/gimli#468]
This would likely make it possible for LLVM to optimize a division away which accounts for ~30% of the time in `generate_row`. I don't see much use for it anyway.

https://github.com/gimli-rs/gimli/blob/1e49ffc9af4ec64a1b7316924d73c933dd7157c5/src/write/line.rs#L471

and

https://github.com/gimli-rs/gimli/blob/1e49ffc9af4ec64a1b7316924d73c933dd7157c5/src/write/line.rs#L475

**Comment by philipc** [comment]
Alternatively, we could do something like https://github.com/gimli-rs/gimli/pull/276/commits/35c7750293a1d299f143a8d389cffe3e10261505 and rely on branch prediction.
