### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by akshat-khare** [gimli-rs/gimli#471]
Hi!
I am new to rust and gimli. I need to use gimli for a project and I followed basic tutorials of rust to understand rust.  I did the following
` cargo new gimlitest2`  
 `cd gimlitest2`  
Wrote gimli = "0.20.0" in Cargo.toml
`cargo build  `  
`cargo run`    
Until everything run successfully.  
Next I copy and paste contents of https://github.com/gimli-rs/gimli/blob/master/examples/simple.rs to src/main.rs  
running `cargo build` gives following errors:  

`   Compiling gimlitest2 v0.1.0 (/Users/codebat/Documents/tempstuff/gimlitest2)
error[E0432]: unresolved import `object`
 --> src/main.rs:3:5
  |
3 | use object::Object;
  |     ^^^^^^ use of undeclared type or module `object`

error[E0433]: failed to resolve: use of undeclared type or module `memmap`
 --> src/main.rs:9:29
  |
9 |         let mmap = unsafe { memmap::Mmap::map(&file).unwrap() };
  |                             ^^^^^^ use of undeclared type or module `memmap`

error[E0433]: failed to resolve: use of undeclared type or module `object`
  --> src/main.rs:10:22
   |
10 |         let object = object::File::parse(&*mmap).unwrap();
   |                      ^^^^^^ use of undeclared type or module `object`

error[E0433]: failed to resolve: use of undeclared type or module `object`
  --> src/main.rs:20:23
   |
20 | fn dump_file(object: &object::File, endian: gimli::RunTimeEndian) -> Result<(), gimli::Error> {
   |                       ^^^^^^ use of undeclared type or module `object`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `gimlitest2`.
`  
I was assuming as a starting program, can someone provide me some help please.
Thanks a lot

**Comment by bjorn3** [comment]
Does `Cargo.toml` contain `edition = "2018"`?

**Comment by akshat-khare** [comment]
Hi bjorn3, Yes it does.  
Quick update: I added two lines in Cargo.toml which led to successful build. My Cargo.toml looks like this:  

```
[package]
name = "gimlitest2"
version = "0.1.0"
authors = ["Akshat Khare <akshat.khare08@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gimli = "0.20.0"
object = "0.9.0"
memmap = "0.7.0"
```

But the output is blank when I run it with `cargo build` followed by `cargo run`. I think I need to supply object file too in cargo run. Would `cargo run <pathToFile>` be the way to run it?  
Thanks.

**Comment by bjorn3** [comment]
> Would cargo run <pathToFile> be the way to run it?

Yes

**Comment by akshat-khare** [comment]
@bjorn3  Would I have to supply object file in argument?

**Comment by bjorn3** [comment]
Yes

**Comment by akshat-khare** [comment]
Thanks

**Comment by bjorn3** [comment]
I think this can be closed.
