### ISSUE TITLE
Re-evaluate deriving Copy

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#48]
It is easy to accidentally make copies when you didn't intend to, which leads to pretty surprising behavior until you figure out what's up. We should go through each place we derive Copy and re-evaluate whether that impl is providing value or not.

cc @kamalmarhubi

**Comment by philipc** [comment]
Related to this, we should should ensure we derive Debug and Clone where appropriate. These can be useful to users of the library, and it's easy to miss adding them if we're not using them internally.

**Comment by philipc** [comment]
According to the rust docs, we should normally derive Copy where possible: https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy. In what case was this a problem?

**Comment by fitzgen** [comment]
Let's close this for now.

@kamalmarhubi: if you can provide more details (see previous comment), we can revisit.
