### ISSUE TITLE
travis results aren't being reported

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#483]
This stopped working about 4 days ago, and there are commits on master missing the travis result, as well as recent PRs.

Maybe we should switch to github actions.

**Comment by fitzgen** [comment]
I like github actions a lot, and they also provide more parallelism at the free tier.

**Comment by philipc** [comment]
I redid the travis auth a while back, and it seems to have fixed things for gimli-rs (cpp_demangle seems to be working too now).  github actions would still be fine, but not something I am going to work on.
