### ISSUE TITLE
Add with overflow when executing `.debug_line` programs

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#506]
Unfortunately, I haven't been able to reduce the size of the test case much, and I also haven't looked at the stack trace or call site in detail. But here's a bug report; will circle back to this.

[debug_line_add_with_overflow.gz](https://github.com/gimli-rs/gimli/files/4635604/debug_line_add_with_overflow.gz)

```rust
    let debug_line = include_bytes!("test/case/above");
    let debug_line = DebugLine::new(&debug_line, LittleEndian);

    let offset = DebugLineOffset(0);
    let address_size = 8;
    if let Ok(program) = debug_line.program(offset, address_size, None, None) {
        let mut rows = program.rows();
        while let Ok(Some(row)) = rows.next_row() {
            let _ = row;
        }
    }
```

**Comment by fitzgen** [comment]
So this is overflow when adding to the current row's address via `DW_LNS_advance_pc`.

It makes sense to me that we should check for this and return an error, but I'm also worried that some toolchain out there might assume wrapping and use that as a hacky way to subtract from the current row's address.

This also comes up with `DW_LNS_fixed_advance_pc`.

**Comment by philipc** [comment]
> I'm also worried that some toolchain out there might assume wrapping and use that as a hacky way to subtract from the current row's address.

We can deal with that if it occurs. It's possible there's consumers that rely on it only increasing, so I think returning an error is better.
