### ISSUE TITLE
Run prettify_attr_value on values returned from Attribute::value()

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#51]
This is trickier than it should be because `Attribute` is `Endian`-less.  We should probably fix that, many of the subtypes of `AttributeValue` need an `Endianity` to be interpreted correctly.

**Comment by fitzgen** [comment]
Easy to keep track of the endian with a `PhantomData`, if needed.

**Comment by khuey** [comment]
Yes. We'd probably want to convert all the `[u8]`s in `AttributeValue` to `EndianBuf`s too.

**Comment by fitzgen** [comment]
Yeah, that is probably the most correct thing to do.

**Comment by philipc** [comment]
@khuey Have you started on this yet? If not, I'll do it, because I need it for dwarfdump.

**Comment by khuey** [comment]
I have not.
