### ISSUE TITLE
 Incorrect address offset

### ISSUE THREAD

**Issue by edsky** [gimli-rs/gimli#528]
Hello, when I used addr, I found that the offset address is different from the normal one, which is about 0x1480. The examples/dwarfdump inside is also similar. You can compare DW_AT_location by DW_TAG_variable.

**Comment by philipc** [comment]
Thanks for the report, but it isn't very clear to me what the problem is. Can you provide steps to reproduce the problem?

**Comment by edsky** [comment]
Sorry i got it wrong
Mistakenly treats two versions of elf files as the same
