### ISSUE TITLE
addr2line is slower than the binutils version

### ISSUE THREAD

**Issue by khuey** [gimli-rs/gimli#53]
By about 60-70% on querying a handful of symbols from libxul.  Two things jump out at me.
1. We spend a lot of time in memset according to perf record (not memcpy, memset)
2. We're chunking writes in 8KB segments, while binutils does 8MB segments.  So we make 120000 read syscalls instead of binutil's ~200 to load libxul.

**Comment by fitzgen** [comment]
The `obj` modules and interface are far from optimized... Very lowest common denominator. We should probably throw some mmap in there too. I think it is reaching the point where that stuff should be another crate that is done Better and For Real and then our example programs can pull it in as a dev dependency.

**Comment by fitzgen** [comment]
@khuey: I moved the `obj` module out to its own crate: https://github.com/gimli-rs/object

Feel free to go to town optimizing it now and reworking it as needed.

**Comment by philipc** [comment]
It looks like mmap and/or xmas-elf solved this?

**Comment by fitzgen** [comment]
> It looks like mmap and/or xmas-elf solved this?

Hopefully?

I was having a lot of trouble running addr2line so I didn't benchmark... I was doing `nm some-executable-with-dwarf` to get symbols and their addresses out and then trying `addr2line -e some-executable-with-dwarf some-symbols-address` to try and get the symbol and line number back out. This doesn't seem to work with `addr2line`, nor our example clone, but works fine with `atos`. What am I doing wrong?

@khuey can you share the command you were using when benchmarking so I can try and repro?

**Comment by khuey** [comment]
I just used `objdump` to find some addresses to lookup.  Running `objdump -C -x --disassemble -l libxul.so | grep callq -C4` should find you some addresses you can look at.

Then run `addr2line -e libxul.so <address>` and it should work.

**Comment by khuey** [comment]
You should try both a single address (to measure the overhead of starting up) and a lot of them (to measure the actual overhead of each lookup).  For the latter case I don't think it's that important that the addresses are all actually valid, as long as some of them are.

**Comment by fitzgen** [comment]
Ok the binutils port of `addr2line` to OSX is garbage... Can't run it successfully without it trying to free a pointer it didn't malloc.

Will bench against `atos` while I'm on OSX.

**Comment by fitzgen** [comment]
Looks like we pretty much blow `atos` out of the water \o/

```
test bench_atos_100_addrs              ... bench: 129,760,722 ns/iter (+/- 3,294,593)
test bench_atos_1_addr                 ... bench: 130,062,593 ns/iter (+/- 4,126,004)
test bench_example_addr2line_100_addrs ... bench:  59,907,993 ns/iter (+/- 1,398,412)
test bench_example_addr2line_1_addr    ... bench:   3,098,922 ns/iter (+/- 282,542)
```

However, I did notice that `atos` will output file:line for many more addresses than we do. This calls for future investigation. Filing an issue.

Benchmark: https://github.com/fitzgen/gimli/blob/bench-addr2line/benches/addr2line.rs

@khuey, if you want to modify the benchmark to use `addr2line` and your own object file and its addresses, I'd love to see the results. If not, I feel pretty confident we can consider this issue resolved.

**Comment by fitzgen** [comment]
> Filing an issue.

https://github.com/gimli-rs/gimli/issues/72

**Comment by philipc** [comment]
I don't think this is a fair comparison until we can output values for all of the addresses. Looking at the code, I think we need to cache the DW_AT_stmt_list value for each compilation unit if we want to have good performance for multiple addresses.

**Comment by jonhoo** [comment]
Only tangentially related, but is the plan to eventually expose `addr2line` as a library method contained within gimli? I want to write a Rust program that parses the output of `perf script`, and it'd be super handy to be able to hand a file to gimli (like in the bootstrapping of the `addr2line` example code), and then simply call `handle.addr2line(addr)` for each address I come across. I *could* copy all the `addr2line` logic into my code, but it seems neater for this to be something gimli provides. Maybe gimli could even cache commonly looked-up addresses or something? Or other internally re-usable information?

**Comment by philipc** [comment]
I do want more higher level library methods in gimli, and parts of addr2line qualify for that. We want to keep gimli independent of the object file parser though, so you'll still need to pass in sections, rather than a file. I think we'll add some caching, but I'm not sure what exactly. If you have a vision for what these higher level methods should be, then patches are welcome. Otherwise, we'll get there eventually :) Currently I don't have a good feel for how to design it so that it's useful for a broad range of consumers. So my worry is that if we simply copy the addr2line code in, then it will be too specific to the addr2line use case, and other consumers will have to reimplement parts of it anyway. Looking at other DWARF libraries might give some ideas.

**Comment by fitzgen** [comment]
My thoughts on the matter are captured by @philipc's comment pretty well.

I'd like to be somewhat conservative about what abstractions we put in, and stick to only the axioms and basic building blocks we currently have, until we have a better idea of what abstractions are broadly useful.

One thing we might consider would be splitting the example programs (or maybe just `addr2line`?) out into their own crates, that could be used either as an executable or a library themselves. Thoughts?

**Comment by philipc** [comment]
> One thing we might consider would be splitting the example programs (or maybe just addr2line?) out into their own crates, that could be used either as an executable or a library themselves. Thoughts?

Sounds fine to me. That should solve @jonhoo's immediate needs.

**Comment by jonhoo** [comment]
Ah, yes, that would be a perfect solution for my use-case! For the application I have in mind, I *only* need the line information (at least currently), and so having a crate for the tool would do nicely. In terms of API, the only thing I would advocate for is the ability to somewhat efficiently do multiple address lookups for a single file/symbol setup. I don't know what internal computation is shared between multiple invocations, but I suspect there's a fair bit?

**Comment by fitzgen** [comment]
@jonhoo I've made https://github.com/gimli-rs/addr2line, which copied `examples/addr2line.rs` into its own repo. Please send pull requests separating the executable bits and argument parsing from the library :)

**Comment by jonhoo** [comment]
@fitzgen Done. See https://github.com/gimli-rs/addr2line/pull/1.

**Comment by jonhoo** [comment]
We should probably also re-file this bug there?

**Comment by philipc** [comment]
Re-filed as https://github.com/gimli-rs/addr2line/issues/2.
