### ISSUE TITLE
no method named `as_debug_info_offset` found for struct `gimli::DebugInfoOffset`

### ISSUE THREAD

**Issue by viveksjain** [gimli-rs/gimli#533]
Hi, rust newbie here so may be missing something straightforward. But I was trying out the simple examples https://github.com/gimli-rs/gimli/blob/master/examples/simple_line.rs and https://github.com/gimli-rs/gimli/blob/master/examples/simple.rs, and they failed with
```
error[E0599]: no method named `as_debug_info_offset` found for struct `gimli::DebugInfoOffset` in the current scope
  --> src/main.rs:49:29
   |
49 |             header.offset().as_debug_info_offset().unwrap().0
   |                             ^^^^^^^^^^^^^^^^^^^^ method not found in `gimli::DebugInfoOffset`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

(This is on newly installed rust version, created new cargo project and added necessary deps gimli, object, mmap.)
Since it is already a `DebugInfoOffset`, I just tried removing `.as_debug_info_offset().unwrap()` and it seems to work just fine after that, although I am not sure if that is the correct fix.

**Comment by philipc** [comment]
`gimli` does not have a stable ABI, so you'll need to use a version of the example that matches the crate version you are using, such as https://github.com/gimli-rs/gimli/blob/0.22.0/examples/simple.rs

**Comment by viveksjain** [comment]
Ah I should have realized, thanks for the quick response! Would be cool if e.g. https://docs.rs/gimli/0.22.0/gimli/read/index.html linked to the same version branch as the crate version, but will leave it to you wonderful folks to decide if that is worth doing.

**Comment by philipc** [comment]
Ah that'd be a good idea. I'm not sure if there is a way we can do that automatically though. rustdoc doesn't seem to include the example source, so we'd have to manually update the url to point to the tag for every release.

**Comment by viveksjain** [comment]
Some googling turns up https://crates.io/crates/cargo-version-sync which may help.

BTW love the name `gimli` 😄
