### ISSUE TITLE
EntriesTreeIter doesn't implement FallibleIterator

### ISSUE THREAD

**Issue by RReverser** [gimli-rs/gimli#536]
Unlike other similar iterators, `EntriesTreeIter` doesn't implement `FallibleIterator` but only inherent `next` method, which makes it harder to use.

I don't suppose there is any technical reason why it couldn't be a fallible iterator like the rest?

**Comment by RReverser** [comment]
Oh... I see, there is a lifetime mismatch :/

**Comment by RReverser** [comment]
Well at least it can be made to work for references, which I suppose is good enough in most cases (at least it suffices for mine):

```rust
struct EntriesTreeIterWrap<'abbrev, 'unit, 'tree, R: Reader> {
    inner: EntriesTreeIter<'abbrev, 'unit, 'tree, R>,
}

impl<'abbrev, 'unit, 'tree, 'me, R: Reader> FallibleIterator
    for &'me EntriesTreeIterWrap<'abbrev, 'unit, 'tree, R>
{
    type Item = EntriesTreeNode<'abbrev, 'unit, 'me, R>;
    type Error = Error;

    fn next(&mut self) -> Result<Option<Self::Item>, Self::Error> {
        self.inner.next()
    }
}
```

**Comment by philipc** [comment]
That still gives lifetime errors for me. Can you submit a PR with your change?

**Comment by DickButtWorldwide** [comment]
Any updates on this?

**Comment by RReverser** [comment]
@philipc You're right, that still doesn't seem to work.
