### ISSUE TITLE
Are static vars stable for the purposes of CloneStableDeref?

### ISSUE THREAD

**Issue by jsgf** [gimli-rs/gimli#537]
If I have a type like:
```rust
enum MyData {
    Data(Arc<[u8]>),
    Empty,
}

static EMPTY: [u8; 0] = [];

impl Deref for MyData {
    type Target = [u8];

    fn deref(&self) -> &[u8] {
        match self {
        MyData::Data(data) => &data,
        MyData::Empty => &EMPTY[..], // is this valid?
        }
    }
}
```
Is this implementation of `Deref` for the  `Empty` case valid for the purposes of `CloneStableDeref`? Or should it be more like:
```
        Mydata::Empty => unsafe { slice::from_raw_parts(1 as *const u8, 0 },
```

**Comment by bjorn3** [comment]
I think it is fine to use `&EMPTY[..]` though you can simply use `&[]` due to const promotion. (rustc will add a kind of implicit static to make it an `'static` reference)

**Comment by philipc** [comment]
I think `&EMPTY[..]` or `&[]` would be fine but I didn't find any rust documentation that guarantees this.

**Comment by jsgf** [comment]
Would `&[][..]` have a stable address? Mightn't it be just some random address on the stack? Likewise, is there anything to prevent llvm from cloning `EMPTY` if it were inlining `deref`?

I guess it really depends on how the rest of gimli makes use of the `CloneStableDeref` invariant. Does it only apply if the thing returned from `deref` is actually addressable?

I ended up using the `from_raw_parts` variant from an abundance of caution.

**Comment by philipc** [comment]
> I guess it really depends on how the rest of gimli makes use of the CloneStableDeref invariant. Does it only apply if the thing returned from deref is actually addressable?

It needs to be able to do this:
https://github.com/gimli-rs/gimli/blob/d36fcf11c878c8ebfb4da4cad300773869b5b5e4/src/read/endian_reader.rs#L184-L189

I don't know what rust's rules are when `len` is 0. If `slice::from_raw_parts(1 as *const u8, 0)` is valid, what other pointer values are also valid?

**Comment by jsgf** [comment]
https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety has the details but basically the pointer can be any non-null aligned value, and is valid for at least `len` elements. So if len==0, then it just needs to be non-null and aligned.

**Comment by philipc** [comment]
Looks like `SubRange` doesn't actually need to implement `Eq`, so we could remove that.

Not sure there is anything else that needs to be done for this issue? Strictly you should be meeting whatever requirements the `stable_deref_trait` crate specifies, even if gimli's needs are more relaxed.

**Comment by jsgf** [comment]
I think it's fine, or it's a more general Rust question.
