### ISSUE TITLE
A way to walk backwards with entry cursor / tree

### ISSUE THREAD

**Issue by RReverser** [gimli-rs/gimli#538]
I'm not actually sure if this is possible with DWARF, but in case it is - could `EntriesCursor` and `EntriesTree` allow to go backwards?

In particular, I don't even care as much about `prev_entry`/`prev_subling`, but I do occasionally want to be able to go "up" to the DIE's parent. For example, when I got a type reference from a function DIE, I can access the type entry itself, but I would also like to be able to walk through the parents to get the full `DW_TAG_namespace` path.

Right now it looks like the only way to do so is to pre-emptively walk the entire unit and cache those paths, which is rather inefficient.

**Comment by bjorn3** [comment]
Dwarf debug entries only store pointers to the next sibling. They don't store pointers to their previous sibling or parent. Getting access to the parent would be possible by manually keeping a stack of entries while walking the tree.

**Comment by RReverser** [comment]
@bjorn3 AFAIK Gimli uses a DWARF-stored sibling info as an optimisation rather than the only path (https://github.com/gimli-rs/gimli/blob/d36fcf11c878c8ebfb4da4cad300773869b5b5e4/src/read/unit.rs#L2721). But, I guess, in order to move backwards without such info it would have to be able to parse backwards as well, which is difficult to introduce (although not impossible)...

> Getting access to the parent would be possible by manually keeping a stack of entries while walking the tree.

Problem is, as I said, I'm starting with a `UnitOffset` to a specific type entry (e.g. taken from `DW_AT_type` on a `DW_TAG_subprogram`). So in this case I'm not walking the tree, but rather jumping to a specific location and want to move "upwards" from there.

As I said in the issue description, I could pre-emptively walk the entire unit, but this is very inefficient and goes against the common DWARF usage (lazily parsing what you need).

**Comment by bjorn3** [comment]
Without the sibling fast path, gimli has to parse forward until it hits the next sibling. I don't think it is possible to parse backwards as entries don't start with a fixed sequence that doesn't appear in the rest of the entry. Getting the size of entries also requires to look at the first few bytes to get the corresponding `.debug_abbrev` entry.

**Comment by RReverser** [comment]
> I don't think it is possible to parse backwards as entries don't start with a fixed sequence that doesn't appear in the rest of the entry.

Ah that's fair... Hmm, just seems odd that this use-case is not covered by the format, when everything else is optimised for lazy parsing.

**Comment by RReverser** [comment]
Closing as I guess there is indeed not much Gimli can do here. I'll try to recursively walk namespace entries in the unit, storing type offsets in a map but not descending - hopefully that will be still fast enough not to cause issues on large apps.

**Comment by philipc** [comment]
Yeah this is lacking in the DWARF standard. I think the `.gdb_index` section is meant to solve this problem.

**Comment by RReverser** [comment]
Realised that I can't even limit walking only to namespaces, because classes can be nested within each other. Looks like I have to traverse the whole thing just to find the parent chain :(
