### ISSUE TITLE
Failing to parse Firefox libxul.so .debug_aranges due to unexpected version 3 in aranges header

### ISSUE THREAD

**Issue by mstange** [gimli-rs/gimli#559]
Steps to reproduce:

1. Download https://symbols.mozilla.org/libxul.so/99DCE71F78C5366B1745C50AB185EF100/libxul.so.dbg.gz and decompress it.
2. Try to use gimli/addr2line to look up file and line information for an address.

Expected results:
The information should be found.

Actual results:
Gimli returns `UnknownVersion(3)` when iterating over the address ranges headers.

Using `llvm-dwarfdump --debug-aranges libxul.so.dbg` confirms that some of the headers use version 3. The DWARF 5 spec says that the version is always 2.
Output from llvm-dwarfdump: https://gist.github.com/mstange/c580559ef4ad593aca8f6b299af53e6e

Is this the presence of these version 3 headers a bug?
Would it be acceptable to relax the version check?

**Comment by mstange** [comment]
I found the following pieces of llvm code:
 - [This code in `llvm/lib/MC/MCDwarf.cpp`](https://github.com/llvm/llvm-project/blob/56541d13779047d353f6665d33f58456f7943e6e/llvm/lib/MC/MCDwarf.cpp#L880-L881) which always writes version 2.
 - [This code in `llvm/lib/DebugInfo/DWARF/DWARFDebugArangeSet.cpp`](https://github.com/llvm/llvm-project/blob/56541d13779047d353f6665d33f58456f7943e6e/llvm/lib/DebugInfo/DWARF/DWARFDebugArangeSet.cpp#L70) which accepts arbitrary versions during parsing.
 - [This code in `lldb/source/Plugins/SymbolFile/DWARF/DWARFDebugArangeSet.cpp`](https://github.com/llvm/llvm-project/blob/56541d13779047d353f6665d33f58456f7943e6e/lldb/source/Plugins/SymbolFile/DWARF/DWARFDebugArangeSet.cpp#L70-L72) which accepts versions 2 to 5 during parsing.

**Comment by mstange** [comment]
With a relaxed version check, addr2line outputs the correct information.

```
% cargo run --release --example addr2line -- --exe ~/libxul.so.dbg -pCfi 0x5a7dcee
glsl::VertexShaderImpl::run_primitive(char*, unsigned long) at /build/firefox-26DV6q/firefox-89.0+build2/gfx/wr/swgl/src/program.h:72
 (inlined by) draw_quad(int, Texture&, Texture&) at /build/firefox-26DV6q/firefox-89.0+build2/gfx/wr/swgl/src/rasterize.h:1522
```

**Comment by mstange** [comment]
Alternatively, addr2line could ignore information from aranges if parsing aranges fails. It has other sources of range information.

Similarly, symbolic-debuginfo has no problems with this libxul.so file because it doesn't make use of aranges.

**Comment by philipc** [comment]
Looks like a NASM bug fixed in https://github.com/netwide-assembler/nasm/commit/29a61b79876a52fe6b98bd82b5fe1560074dd659

**Comment by mstange** [comment]
Nice find!
