### ISSUE TITLE
Please update "object" dependency to latest version

### ISSUE THREAD

**Issue by olivierlemasle** [gimli-rs/gimli#561]
Please update `object` dependency to its latest version 0.25.3.

This would help Fedora packaging of `object`, `gimli` and crates that depend on latest `object` (as cranelift). Thanks!

**Comment by philipc** [comment]
Do you package the dev dependencies? (I'm aware that an old version of `object` is also used in `addr2line` which is probably where this request is coming from.)

**Comment by olivierlemasle** [comment]
Yes, the dev-dependencies are also packaged, for `gimli` and `addr2line`.
