### ISSUE TITLE
Extend `FileEntry::directory` to return the compilation's current directory as `&CStr` instead of `None`

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#59]
@fitzen suggested:

> impl FileEntry {
>     pub fn directory(&self, header: &LineNumberProgramHeader) -> &'input ffi::CStr;
> }

> Although we need to handle the index == 0 case, which is supposed to mean the compilation's current directory, which we get from the CU DIE... Maybe it should take that as input, too...

**Comment by fitzgen** [comment]
We have the first half already: https://github.com/gimli-rs/gimli/blob/master/src/line.rs#L1175-L1190

It just returns `None` for the compilation's current directory, but it would be nice to grab that attribute off the CU's topmost die.
