### ISSUE TITLE
AttributeSpecification::size may be wrong for DW_FORM_ref_addr in version 2 if word size and address size differ

### ISSUE THREAD

**Issue by mstange** [gimli-rs/gimli#591]
Compare:

https://github.com/gimli-rs/gimli/blob/d20becf924f623a501f24738c35558e6222e6946/src/read/unit.rs#L2102-L2110

and

https://github.com/gimli-rs/gimli/blob/d20becf924f623a501f24738c35558e6222e6946/src/read/abbrev.rs#L448-L451

I think `AttributeSpecification::size` needs to check the encoding version and use `address_size` for the size of `DW_FORM_ref_addr` if the version is 2.

**Comment by philipc** [comment]
Yeah, looks wrong. Are you using this function? I'm inclined to delete it completely.

**Comment by mstange** [comment]
> Are you using this function?

I'm considering it. The first pass over the entries in addr2line (to build the list of outer functions) is still too slow  for my taste, and we spend all the time parsing attributes that we don't need. I'm experimenting with a `skip_attributes` function which reads just enough to know how many bytes to skip and throws out everything else, to see whether that's faster.

**Comment by mstange** [comment]
I gave that a try and it wasn't measurably faster. Deleting this function sounds fine to me.

**Comment by mstange** [comment]
I think it also gives the wrong result for `DW_FORM_flag_present`, which should be zero bytes, not one.
