### ISSUE TITLE
Feature request: Ability to iterate over all entries in the EhHdrTable

### ISSUE THREAD

**Issue by mstange** [gimli-rs/gimli#612]
[`EhHdrTable`](https://docs.rs/gimli/latest/gimli/read/struct.EhHdrTable.html) has various APIs to look up addresses in the table, but I can't find a way to get a list of all entries.

I'm interested in a full list from eh_frame_hdr because I want to use it as a cheap approximation of function start addresses, to synthesize fallback symbols for stripped libraries. I could also get such a list from eh_frame itself, but it would probably take longer to parse.

@main--, @fitzgen, was this an intentional omission, or just something that wasn't needed at the time?

**Comment by philipc** [comment]
I think you should iterate over the FDEs in `eh_frame` instead. I can't imagine it's much slower than `eh_frame_hdr`, and it will work even if `eh_frame_hdr` is missing.

**Comment by mstange** [comment]
Fair enough.

**Comment by philipc** [comment]
Does #619 meet your needs?

**Comment by mstange** [comment]
Yes, I think that does exactly what I need.
