### ISSUE TITLE
Upgrade to indexmap 2?

### ISSUE THREAD

**Issue by cuviper** [gimli-rs/gimli#665]
I would be happy to send a PR upgrading to indexmap 2, and it doesn't even require any code changes, but it would increase the MSRV enough that I'm not sure it would be welcome.

It would require 1.64 when feature `write = ["indexmap"]` is enabled, and at least 1.60 otherwise due to hashbrown's use of new dependency syntax. I don't know if you want to bother with split MSRV, but I also described this in gimli-rs/object#558.

**Comment by philipc** [comment]
The MSRV in this crate is a bit of a mess currently, so I'll take care of this next time I'm doing a release, unless you have a need for it now.

**Comment by cuviper** [comment]
I have no strong need here -- just trying to help upgrade the ecosystem to reduce duplicate dependencies.
