### ISSUE TITLE
UnknownCallFrameInstruction(DwCfa(45))

### ISSUE THREAD

**Issue by krzysiek6d** [gimli-rs/gimli#667]
Hi

On aarch64 arm64v8 I encountered such errors:
UnknownCallFrameInstruction(DwCfa(45))
Seems that 45 points to DW_CFA_GNU_window_save which is not implemented.
Is there any chance for implmenting that?

**Comment by krzysiek6d** [comment]
It seems that it can be also DW_CFA_AARCH64_negate_ra_state - it's value is also 45

**Comment by philipc** [comment]
I can implement if I have time, but it won't be soon. Needing to support different vendors is going to complicate things; it's not something we've handled anywhere yet.

**Comment by philipc** [comment]
Can you test whether #673 meets your needs? I haven't done any testing on it myself yet.

**Comment by krzysiek6d** [comment]
Thanks, I'll check that next week ;)

**Comment by philipc** [comment]
I tested the dwarfdump example on an AArch64 binary produced by clang.
