### ISSUE TITLE
`debug_assert!` problem for wasm-bindgen

### ISSUE THREAD

**Issue by namse** [gimli-rs/gimli#681]
Hello. wasm-bindgen and walrus are using this crate, and there is a particular issue that has arisen, which I would like to discuss.

Currently, when generating the DWARF for wasm in wasm-bindgen, there is an assertion debug_assert! that's triggered at the following location: https://github.com/gimli-rs/gimli/blob/master/src/write/line.rs#L467

Could you please confirm whether this debug_assert is a critical assertion that must be true condition?

related issues
- https://github.com/rustwasm/wasm-bindgen/pull/3483#issuecomment-1594273805
- https://github.com/rustwasm/walrus/issues/247

**Comment by bjorn3** [comment]
Line tables use monotonically increasing addresses. There is no opcode to decrease the address of the next row compared to the previous one. If that assertion fires, the user of gimli tried to produce invalid DWARF debuginfo. Without the assertion I would expect an underflow panic to happen in debug mode when calculating the address increment for the current row.

**Comment by namse** [comment]
Thank you for response. I guess walrus should pass that debug_assert.
I don't have other question so I close this issue.
