### ISSUE TITLE
The storage in `UnwindContext.stack` was changed to a `Vec`

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#683]
#595 changed the storage of `UnwindContext.stack` from an [array](https://github.com/gimli-rs/gimli/pull/595/files#diff-07936eebac4af5b6d91b383a22562daf4b42d4dac698fd0d0301191fa64ec2b8L1768-R1821) to a [`Vec`](https://github.com/gimli-rs/gimli/pull/595/files#diff-07936eebac4af5b6d91b383a22562daf4b42d4dac698fd0d0301191fa64ec2b8R1787). @nbdd0121 Was this an intentional change? I'm inclined to change it back. I think defaulting to a fixed size allocation is preferable.

**Comment by nbdd0121** [comment]
IIRC In majority of cases of unwinding this stack is not needed. The previous 4-element storage consumes quite a bit of stack. If you are allowed to allocate then it's better off to just use a Vec so that it doesn't allocate in fast path.

**Comment by philipc** [comment]
> In majority of cases of unwinding this stack is not needed.

It always needs at least one element for the rules, so it needs to allocate in every case: https://github.com/gimli-rs/gimli/blob/531636d6fed8fc1f068fe34eaa81c604debb15a3/src/read/cfi.rs#L2010

> The previous 4-element storage consumes quite a bit of stack.

That's why the documentation and example suggested putting the `UnwindContext` on the heap. And if you put the `UnwindContext` on the heap and reuse it, then allocating it is a once only cost.

The advantage using only 4 elements is that it puts an upper bound on memory usage, and it is sufficient for all CFI in practice.

**Comment by nbdd0121** [comment]
Ah, the current row. How about store the current row along side with the stack then?
