### ISSUE TITLE
Gimli cannot parse multiple units in aarch64

### ISSUE THREAD

**Issue by liutao-liu** [gimli-rs/gimli#689]
As shown in the following figure, when there are multiple units, Gimli parses only the first unit from the ELF file.
![image](https://github.com/gimli-rs/gimli/assets/10509166/6b3b8684-e9a6-452f-934c-1422fbb8ab60)

**Comment by philipc** [comment]
gimli definitely can parse multiple units, so you'll need to give more information on how to reproduce the problem you are seeing.

**Comment by liutao-liu** [comment]
My running environment: aarch64 + ubuntu 20.0.4 TSL
I run the simple_line.rs example to parse my object. This object has two units, but simple_line.rs can only parse the first unit, as shown in the following figure.

![image](https://github.com/gimli-rs/gimli/assets/10509166/c4c1704c-73e1-47f5-b64f-a01d3f9ae1df)

**Comment by philipc** [comment]
Can you provide an example file?

**Comment by liutao-liu** [comment]
My running environment: aarch64 + ubuntu 20.04 TSL
Gimli version:0.28.1

The example in simple_line.rs attempt to parse all units in an object file.
Then i run the example in simple_line.rs to parse my object. This object has two units, but simple_line.rs can only parse the first unit, as shown in the following figure.

![image](https://github.com/gimli-rs/gimli/assets/10509166/f9248b97-820a-47ce-aaff-28c94d9c9011)

**Comment by philipc** [comment]
Please attach the binary `a.aout` so that I can reproduce the issue.

**Comment by liutao-liu** [comment]
Sorry, I can't offer a.out. The example I've given is simple, and you can compile it very quickly by following the steps above.

**Comment by philipc** [comment]
It's simple to add the file to this issue, but okay, I'll have to wait until next week to look at it then.

**Comment by philipc** [comment]
The problem is that you are building a relocatable object file, and the `simple_line` example does not process relocations, so various references in the DWARF are read as zeroes. If you build an executable then it works fine: `clang test.ll -o a.out`
Alternatively, the `dwarfdump` example does process relocations.
