### ISSUE TITLE
Re-enable coveralls.io

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#69]
For whatever reason, coveralls.io just stopped running for us a while back, so I removed the badge and all that. The .travis.yml is actually still running coverage stuff, AFAICT. We should figure out how to get the hook setup correctly again.

**Comment by fitzgen** [comment]
That PR did not seem to work. https://coveralls.io/github/gimli-rs/gimli still looks like it is waiting for the first push...

**Comment by fitzgen** [comment]
serde uses travis-cargo and uploads to coveralls.io and it seems to work: https://github.com/serde-rs/serde/blob/master/.travis.yml#L32

reges does not use travis-cargo, but has a custom kcov + coveralls.io script: https://github.com/rust-lang-nursery/regex/blob/master/.travis.yml#L47

**Comment by philipc** [comment]
It looks like `travis-cargo coveralls` is broken, it's not running kcov correctly: https://travis-ci.org/gimli-rs/gimli/jobs/155266949#L1087. serde has the same problem: https://travis-ci.org/serde-rs/serde/jobs/155590105#L1006 and the last successful coveralls build for serde was 7 Jul.

**Comment by philipc** [comment]
See https://github.com/huonw/travis-cargo/issues/58

**Comment by fitzgen** [comment]
Fixed by #75
