### ISSUE TITLE
addr2line should use DIE information

### ISSUE THREAD

**Issue by philipc** [gimli-rs/gimli#80]
In the absence of `.debug_line` information, there is still other file and and address information in `.debug_info` that we can use to give vague information about the address.

**Comment by jonhoo** [comment]
Given that `addr2line` has now moved to its own repository, it would probably be good to move this issue to https://github.com/gimli-rs/addr2line with a backpointer to here.

**Comment by philipc** [comment]
Moved to https://github.com/gimli-rs/addr2line/issues/3.
