### ISSUE TITLE
Add support for dynamic endianity

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#84]
@philipc says:

> I think we still need something that is runtime selectable as well though. https://github.com/gimli-rs/gimli/blob/master/examples/dwarfdump.rs#L79-L83 is fine for simple utilities, but we need some way to stop the endianity bubbling up through all the APIs.

**Comment by fitzgen** [comment]
@philipc: What if we made `BigEndian` and `LittleEndian` into zero sized structs with no members and then made `DynamicEndian` an enum between the two?

```rust
#[derive(all the things)]
pub struct CompileTimeEndian<B: byteorder::ByteOrder>(PhantomData<B>);

impl<B: byteorder::ByteOrder> byteorder::ByteOrder for CompileTimeEndian<B> {
    // ...
}

pub type BigEndian = CompileTimeEndian<byteorder::BigEndian>;
pub type LittleEndian = CompileTimeEndian<byteorder::LittleEndian>;

pub enum RunTimeEndian {
    Big(BigEndian),
    Little(LittleEndian),
}

impl byteorder::ByteOrder for RunTimeEndian {
    // ...
}
```

**Comment by fitzgen** [comment]
I think this means we will need all the various `read_u64` methods to take `&self`, so we can't just use `ByteOrder` instead of `Endianity` as #155 proposes.

**Comment by philipc** [comment]
> What if we made BigEndian and LittleEndian into zero sized structs with no members and then made DynamicEndian an enum between the two?

Yes, that is what I was thinking, and agree that it means we still need `Endianity`.
