### ISSUE TITLE
Figure out how to get coveralls.io to understand benches, integration tests, and examples

### ISSUE THREAD

**Issue by fitzgen** [gimli-rs/gimli#91]
Right now, AFAICT, it only considers what is run for `#[test]`s in the main library, not anything under the `tests/` directory, `examples/`, or `benches/`.

It would be nice to expand to cover them too.

**Comment by fitzgen** [comment]
Can we close this one, @philipc ?

**Comment by philipc** [comment]
Yeah, hopefully #103 will make this usable.
